// Auto-generated from products.html — MAZI Hardware product catalog
// Each key is a stable product id used in product-detail.html?id=<id>
const PRODUCTS = {
  'tiles-2': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'PLAIN WHITE', desc: '600x1200mm 600x600mm 300x300mm | Glossy, Matte Finish | Indoor/Outdoor', image: 'img/tiles catalog/2.jpg', alt: 'Floor Tiles' },
  'tiles-3': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'NATURAL GOLDEN BLUE R1', desc: '600x1200mm | Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/3.jpg', alt: 'Floor Tiles' },
  'tiles-4': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'AURORA GREY-1', desc: '600x1200mm | Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/4.jpg', alt: 'Floor Tiles' },
  'tiles-5': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'ARBESCATO BROWN R1', desc: '600x1200mm | Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/5.jpg', alt: 'Floor Tiles' },
  'tiles-6': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'SUNVERDE AQUA-1', desc: '600x1200mm | Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/6.jpg', alt: 'Floor Tiles' },
  'tiles-7': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'AEDEA', desc: '600x600mm 300x600mm| Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/7.jpg', alt: 'Floor Tiles' },
  'tiles-8': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'AEDEA-1', desc: '600x1200mm| Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/8.jpg', alt: 'Floor Tiles' },
  'tiles-9': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'ONYX ROOSVELT ICE', desc: '600x600mm| Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/9.jpg', alt: 'Floor Tiles' },
  'tiles-10': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'ONYX ROOSVELT GREY', desc: '600x600mm| Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/10.jpg', alt: 'Floor Tiles' },
  'tiles-11': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'ANTHRACITE CREMA', desc: '600x600mm| Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/11.jpg', alt: 'Floor Tiles' },
  'tiles-12': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'ANTHRACITE IVORY', desc: '600x600mm| Matte Finish | Indoor/Outdoor', image: 'img/tiles catalog/12.jpg', alt: 'Floor Tiles' },
  'tiles-13': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'MEGNITE GREY', desc: '600x600mm| Matte Finish | Indoor/Outdoor', image: 'img/tiles catalog/13.jpg', alt: 'Floor Tiles' },
  'tiles-14': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'OAK WOOD CAMEL', desc: '600x600mm| Matte Finish | Indoor/Outdoor', image: 'img/tiles catalog/14.jpg', alt: 'Floor Tiles' },
  'tiles-15': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'OSLO GRIS', desc: '600x600mm| Matte Finish | Indoor/Outdoor', image: 'img/tiles catalog/15.jpg', alt: 'Floor Tiles' },
  'tiles-16': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'CENTO BIANCO', desc: '600x600mm| Matte Finish | Indoor/Outdoor', image: 'img/tiles catalog/16.jpg', alt: 'Floor Tiles' },
  'tiles-17': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'ORENTA NATURAL', desc: '600x600mm| Matte Finish | Indoor/Outdoor', image: 'img/tiles catalog/17.jpg', alt: 'Floor Tiles' },
  'tiles-18': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'SIRRIZO PEARL', desc: '600x600mm| Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/18.jpg', alt: 'Floor Tiles' },
  'tiles-19': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'ECHO BLUE', desc: '600x1200mm | Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/19.jpg', alt: 'Floor Tiles' },
  'tiles-20': { category: 'tiles', categoryLabel: 'Tiles', badge: 'Tiles', name: 'DALIM GREY', desc: '600x1200mm | Glossy Finish | Indoor/Outdoor', image: 'img/tiles catalog/20.jpg', alt: 'Floor Tiles' },
  'uv-marble-2': { category: 'uv-marble', categoryLabel: 'UV Marble', badge: 'UV MARBLE SHEETS', name: 'GLOSSY', desc: '4 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/uv marble sheets catalog/2.jpg', alt: 'Uv Marble Sheets' },
  'uv-marble-3': { category: 'uv-marble', categoryLabel: 'UV Marble', badge: 'UV MARBLE SHEETS', name: 'GLOSSY', desc: '4 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/uv marble sheets catalog/3.jpg', alt: 'Uv Marble Sheets' },
  'uv-marble-4': { category: 'uv-marble', categoryLabel: 'UV Marble', badge: 'UV MARBLE SHEETS', name: 'GLOSSY', desc: '4 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/uv marble sheets catalog/4.jpg', alt: 'Uv Marble Sheets' },
  'uv-marble-5': { category: 'uv-marble', categoryLabel: 'UV Marble', badge: 'UV MARBLE SHEETS', name: 'GLOSSY', desc: '4 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/uv marble sheets catalog/5.jpg', alt: 'Uv Marble Sheets' },
  'uv-marble-6': { category: 'uv-marble', categoryLabel: 'UV Marble', badge: 'UV MARBLE SHEETS', name: 'GLOSSY', desc: '4 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/uv marble sheets catalog/6.jpg', alt: 'Uv Marble Sheets' },
  'uv-marble-7': { category: 'uv-marble', categoryLabel: 'UV Marble', badge: 'UV MARBLE SHEETS', name: 'GLOSSY', desc: '4 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/uv marble sheets catalog/7.jpg', alt: 'Uv Marble Sheets' },
  'uv-marble-8': { category: 'uv-marble', categoryLabel: 'UV Marble', badge: 'UV MARBLE SHEETS', name: 'GLOSSY', desc: '4 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/uv marble sheets catalog/8.jpg', alt: 'Uv Marble Sheets' },
  'uv-marble-9': { category: 'uv-marble', categoryLabel: 'UV Marble', badge: 'UV MARBLE SHEETS', name: 'MATTE', desc: '4 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/uv marble sheets catalog/9.jpg', alt: 'Uv Marble Sheets' },
  'uv-marble-10': { category: 'uv-marble', categoryLabel: 'UV Marble', badge: 'UV MARBLE SHEETS', name: 'MATTE', desc: '4 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/uv marble sheets catalog/10.jpg', alt: 'Uv Marble Sheets' },
  'ceiling-2': { category: 'ceiling', categoryLabel: 'Ceiling Panel', badge: 'CEILING PANEL', name: 'DS-098', desc: 'Size: 300*8*5800mm glossy', image: 'img/ceiling panel/2.jpg', alt: 'Uv Marble Sheets' },
  'ceiling-3': { category: 'ceiling', categoryLabel: 'Ceiling Panel', badge: 'CEILING PANEL', name: 'DS-217', desc: 'Size: 300*8*5800mm laminated', image: 'img/ceiling panel/3.jpg', alt: 'Uv Marble Sheets' },
  'ceiling-4': { category: 'ceiling', categoryLabel: 'Ceiling Panel', badge: 'CEILING PANEL', name: 'DS-001', desc: 'Size: 300*8*5800mm printing', image: 'img/ceiling panel/4.jpg', alt: 'Uv Marble Sheets' },
  'ceiling-5': { category: 'ceiling', categoryLabel: 'Ceiling Panel', badge: 'CEILING PANEL', name: 'DS-002', desc: 'Size: 300*8*5800mm printing', image: 'img/ceiling panel/5.jpg', alt: 'Uv Marble Sheets' },
  'parquet-2': { category: 'parquet', categoryLabel: 'Parquet', badge: 'Parquet', name: 'PINEWOOD', desc: 'Size: 183 x 1220 x 4.5+ 1mm', image: 'img/parquet/2.jpg', alt: 'Parquet' },
  'parquet-3': { category: 'parquet', categoryLabel: 'Parquet', badge: 'Parquet', name: 'SEIRRA OAK', desc: 'Size: 183 x 1220 x 4.5+ 1mm', image: 'img/parquet/3.jpg', alt: 'Parquet' },
  'parquet-4': { category: 'parquet', categoryLabel: 'Parquet', badge: 'Parquet', name: 'ORANGE', desc: 'Size: 183 x 1220 x 4.5+ 1mm', image: 'img/parquet/4.jpg', alt: 'Parquet' },
  'parquet-5': { category: 'parquet', categoryLabel: 'Parquet', badge: 'Parquet', name: 'SILVER OAK', desc: 'Size: 183 x 1220 x 4.5+ 1mm', image: 'img/parquet/5.jpg', alt: 'Parquet' },
  'parquet-6': { category: 'parquet', categoryLabel: 'Parquet', badge: 'Parquet', name: 'HAZELNUT', desc: 'Size: 183 x 1220 x 4.5+ 1mm', image: 'img/parquet/6.jpg', alt: 'Parquet' },
  'parquet-7': { category: 'parquet', categoryLabel: 'Parquet', badge: 'Parquet', name: 'ALMOND WHITE', desc: 'Size: 183 x 1220 x 4.5+ 1mm', image: 'img/parquet/7.jpg', alt: 'Parquet' },
  'parquet-8': { category: 'parquet', categoryLabel: 'Parquet', badge: 'Parquet', name: 'BLACK SESAME', desc: 'Size: 183 x 1220 x 4.5+ 1mm', image: 'img/parquet/8.jpg', alt: 'Parquet' },
  'pvc-wall-2': { category: 'pvc-wall', categoryLabel: 'PVC Wall Panel', badge: 'PVC WALL PANEL', name: 'WALL PANEL', desc: '2 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/pvc wall panel/2.jpg', alt: 'Parquet' },
  'pvc-wall-3': { category: 'pvc-wall', categoryLabel: 'PVC Wall Panel', badge: 'PVC WALL PANEL', name: 'WALL PANEL', desc: '2 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/pvc wall panel/3.jpg', alt: 'Parquet' },
  'pvc-wall-4': { category: 'pvc-wall', categoryLabel: 'PVC Wall Panel', badge: 'PVC WALL PANEL', name: 'WALL PANEL', desc: '2 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/pvc wall panel/4.jpg', alt: 'Parquet' },
  'pvc-wall-5': { category: 'pvc-wall', categoryLabel: 'PVC Wall Panel', badge: 'PVC WALL PANEL', name: 'WALL PANEL', desc: '2 ft Width | 9.5 ft Length | 3mm Thickness', image: 'img/pvc wall panel/5.jpg', alt: 'Parquet' },
  'wpc-2': { category: 'wpc', categoryLabel: 'WPC Wall Panel', badge: 'WPC WALL PANEL', name: 'B061', desc: 'WPC-150 x 23mm x 9.5ft-0', image: 'img/wpc/2.jpg', alt: 'Parquet' },
  'wpc-3': { category: 'wpc', categoryLabel: 'WPC Wall Panel', badge: 'WPC WALL PANEL', name: 'P109', desc: 'WPC-150 x 23mm x 9.5ft-0', image: 'img/wpc/3.jpg', alt: 'Parquet' },
  'wpc-4': { category: 'wpc', categoryLabel: 'WPC Wall Panel', badge: 'WPC WALL PANEL', name: 'P104', desc: 'WPC-150 x 23mm x 9.5ft-0', image: 'img/wpc/4.jpg', alt: 'Parquet' },
  'wpc-5': { category: 'wpc', categoryLabel: 'WPC Wall Panel', badge: 'WPC WALL PANEL', name: 'M2055', desc: 'WPC-150 x 23mm x 9.5ft-0', image: 'img/wpc/5.jpg', alt: 'Parquet' },
  'wpc-6': { category: 'wpc', categoryLabel: 'WPC Wall Panel', badge: 'WPC WALL PANEL', name: 'M2055', desc: 'WPC-150 x 23mm x 9.5ft-0', image: 'img/wpc/6.jpg', alt: 'Parquet' },
  'wpc-7': { category: 'wpc', categoryLabel: 'WPC Wall Panel', badge: 'WPC WALL PANEL', name: 'P133', desc: 'WPC-150 x 23mm x 9.5ft-0', image: 'img/wpc/7.jpg', alt: 'Parquet' },
};

const PRODUCT_ORDER = [
  'tiles-2', 'tiles-3', 'tiles-4', 'tiles-5', 'tiles-6', 'tiles-7', 'tiles-8', 'tiles-9', 'tiles-10', 'tiles-11', 'tiles-12', 'tiles-13', 'tiles-14', 'tiles-15', 'tiles-16', 'tiles-17', 'tiles-18', 'tiles-19', 'tiles-20', 'uv-marble-2', 'uv-marble-3', 'uv-marble-4', 'uv-marble-5', 'uv-marble-6', 'uv-marble-7', 'uv-marble-8', 'uv-marble-9', 'uv-marble-10', 'ceiling-2', 'ceiling-3', 'ceiling-4', 'ceiling-5', 'parquet-2', 'parquet-3', 'parquet-4', 'parquet-5', 'parquet-6', 'parquet-7', 'parquet-8', 'pvc-wall-2', 'pvc-wall-3', 'pvc-wall-4', 'pvc-wall-5', 'wpc-2', 'wpc-3', 'wpc-4', 'wpc-5', 'wpc-6', 'wpc-7'
];
